### PR TITLE
Fixed a few bugs, added support for functions.config(), stubs for functions.auth

### PR DESCRIPTION
**Pull request by jspri**

### CODE REVIEW

**Comment by christianalfoni** [comment]
This is great @Crazometer , thanks a bunch for contributing! Will make a minor adjustment by adding a default `httpListener` which sends a message back to client that no `onReq` has been "activated". But other than that, sweet!

I also think there is a bug on the `onWrite`, where you only have `/articles/{key}` for example. I built that mock for a specific use case... anyways, will fix it when I find some time, just though I would mention it.

Thinking of it... maybe "mock" is the wrong name here. MAybe `firebase-functions-local` or something would be better, cause it is not purely a mock, it just simulates production :)

What you think?

**Comment by jspri** [comment]
`firebase-functions-local` sounds good to me.

I'm going to hack out a few more adjustments to suit my needs that I'll run by you in a bit.

**Comment by christianalfoni** [comment]
Published 2.0.0, check README for final changes :)

**Comment by christianalfoni** [comment]
Excellent!

**Pull request merged**
